name: Deploy

on:
  push:
    tags:
      - v2.0.0-alpha*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cp -r docs .temp
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false
      - run: mkdir -p v2-alpha
      - run: cp -rf .temp/* v2-alpha
      - run: rm -r .temp
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
      - run: git add v2-alpha
      - run: git commit --message "${{ github.ref_name }}"
      - run: git push
